spring:
  config:
    import: optional:configserver:http://config-service:8888
  datasource:
    url: jdbc:mysql://mysql:3306/keynote_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/conferencehub
          jwk-set-uri: http://keycloak:8080/realms/conferencehub/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

